# Travis-CI Build for dynamitey 
# see travis-ci.org for details

language: csharp
matrix:
  include:
    - os: linux
      dist: xenial
      sudo: required
    - os: osx
      osx_image: "xcode8.3"

solution: FSharp.Interop.NullOptAble.sln

dotnet: 2.2

install:
  - dotnet restore

script:
  - dotnet test